### ISSUE TITLE
Error with Rails 5

### ISSUE THREAD

**Issue by tripodrob** [scambra/recordselect#14]
I get the following error in Rails 5: 

gems/recordselect-3.5.0/app/views/record_select/_browse.html.erb

ActionView::Template::Error (Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.):
    1: <% url_options = params.merge(:controller => controller, :action => :browse, :page => 1, :update => 1) -%>
    2: <%= form_tag url_options, {:method => :get, :remote => true, :id => record_select_search_id}  -%>
    3:   <%= text_field_tag 'search', params[:search], :autocomplete => 'off', :class => 'text-input' %>
    4:   <%= submit_tag 'search', :class => "search_submit" %>
    5: </form>

**Comment by tripodrob** [comment]
Would it be sufficient to whitelist the parameters in the partials like this (_search.html):

<% url_options = params.merge(:controller => controller, :action => :browse, :page => 1, :update => 1) -%>
<%= form_tag url_options.permit(:controller, :action, :search, :update), {:method => :get, :remote => true, :id => record_select_search_id}  -%>

**Comment by scambra** [comment]
I'm not sure it's enough, record select allows to setup custom parameters on record_select_field:

https://github.com/scambra/recordselect/blob/master/lib/record_select/helpers/record_select_helper.rb#L46

This params are sent to browse action, so they must be sent again. Probably a helper method to define which params to permit should be added, so we don't permit everything, for security. If someone adds params to record_select_field, same params should be added to this helper.

**Comment by scambra** [comment]
I couldn't test yet, please test it and I will release new version

**Comment by tripodrob** [comment]
It appears to work for me.  Thanks!

**Comment by scambra** [comment]
Releasing 3.6.0, as rails 3 is not supported anymore
